### ISSUE TITLE
 No UI to Access

### ISSUE THREAD

**Issue by hakarune** [buanet/ioBroker.docker#253] opened 2022-03-17 06:31 UTC
I have tried multiple different ports configs and env optoins, but I can not gain access to any sort of UI through the web interface and have even tried manually installing the web and admin plugins, but still nothing.

**Comment by buanet** [comment] 2022-03-17 08:04
I'm sorry. I cannot help you with that as long as you do not post any configs you tried together with the full log of your fresh container after it is started...

Start with the system you are using as your Docker host. Post the command/ compose file/ ui screenshot you use for deploying the container. Say something about the network you are using (bridge, host, macvlan?). Post the log of a container startup.

Are you familiar with Docker or is that all new for you? 

Regards,
André

**Comment by hakarune** [comment] 2022-03-18 06:33
> I'm sorry. I cannot help you with that as long as you do not post any configs you tried together with the full log of your fresh container after it is started...
> 
> Start with the system you are using as your Docker host. Post the command/ compose file/ ui screenshot you use for deploying the container. Say something about the network you are using (bridge, host, macvlan?). Post the log of a container startup.
> 
> Are you familiar with Docker or is that all new for you?
> 
> Regards, André

I'm fairly familiar with Docker and been using it a long time, I have a headless Debian running OpenmediaVault NAS with 2 different RAID setups and a single mechanical for holding things like Docker configs/volumes. I use Portainer as my docker controller.

My network: multiple VLANs controlled via the router. Server for docker is on main VLAN and uses mostly bridge for all networks within docker.

Here is the most recent config (was trying to get iobroker.webui to work so I could access the system)

```
version: '2'
services:
 iobroker:
    image: buanet/iobroker
    network_mode: bridge
    container_name: iobroker_mar2
    hostname: iobroker
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/Los_Angeles
        - UMASK_SET=002 #optional
        - CLEAN_TMP_DIR=1
        - VIRTUAL_HOST=iobroker.local
        - VIRTUAL_PORT=8085
    volumes:
        - /sharedfolders/Alt_External/docker_configs/iobroker:/opt/iobroker
    ports:
        - 8085:8081
        - 8082:8082
    logging:
        driver: syslog
        options:
               tag: iobroker
               syslog-address: udp://10.10.10.51:514
    restart: unless-stopped

```

Here is the first run log (re-pulled and re-deployed fresh):
 
```
--------------------------------------------------------------------------------
-------------------------     2022-03-17 23:22:49      -------------------------
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                 Welcome to your ioBroker-container!                  -----
-----                    Startupscript is now running.                     -----
-----                          Please be patient!                          -----
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                        Debugging information                         -----
-----                                                                      -----
-----                                System                                -----
-----                    arch:                x86_64                       -----
-----                    hostname:            iobroker                     -----
-----                                                                      -----
-----                             Docker-Image                             -----
-----                    image:               v6.1.0                       -----
-----                    build:               2022-03-14T07:29:48+00:00    -----
-----                                                                      -----
-----                               Versions                               -----
-----                    node:                v14.19.0                     -----
-----                    npm:                 6.14.16                      -----
-----                                                                      -----
-----                                 ENV                                  -----
-----                    SETGID:              1000                         -----
-----                    SETUID:              1000                         -----
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                  Step 1 of 5: Preparing container                   -----
--------------------------------------------------------------------------------
 
Updating Linux packages on first run...
dpkg-preconfigure: unable to re-open stdin: 
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 32069 files and directories currently installed.)
Preparing to unpack .../libssl1.1_1.1.1k-1+deb11u2_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1k-1+deb11u2) over (1.1.1k-1+deb11u1) ...
Setting up libssl1.1:amd64 (1.1.1k-1+deb11u2) ...
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 32069 files and directories currently installed.)
Preparing to unpack .../nodejs_14.19.1-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (14.19.1-deb-1nodesource1) over (14.19.0-deb-1nodesource1) ...
Preparing to unpack .../openssl_1.1.1k-1+deb11u2_amd64.deb ...
Unpacking openssl (1.1.1k-1+deb11u2) over (1.1.1k-1+deb11u1) ...
Setting up nodejs (14.19.1-deb-1nodesource1) ...
Setting up openssl (1.1.1k-1+deb11u2) ...
Processing triggers for libc-bin (2.31-13+deb11u2) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Done.
 
Registering maintenance script as command...
Done.
 
--------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker installation             -----
--------------------------------------------------------------------------------
 
Existing installation of ioBroker detected in /opt/iobroker.
 
--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
(Re)Setting folder permissions (This might take a while! Please be patient!)...
Done.
 
Fixing "sudo-bug" by replacing sudo in iobroker with gosu...
Done.
 
Hostname in ioBroker does not match the hostname of this container.
Updating hostname to  iobroker...
/opt/scripts/iobroker_startup.sh: line 205: /usr/bin/iobroker: Permission denied
iobroker host <hostname>

Set host to given hostname


:
  iobroker host this               Initialize current host
  iobroker host set <hostname>     Set host with specified hostname
  iobroker host remove <hostname>  Remove host with specified hostname

Options:
  --help  Show help  [boolean]

Not enough non-option arguments: got 0, need at least 1
Done.
 
--------------------------------------------------------------------------------
-----                Step 4 of 5: Applying special settings                -----
--------------------------------------------------------------------------------
 
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).
 
--------------------------------------------------------------------------------
-----                    Step 5 of 5: ioBroker startup                     -----
--------------------------------------------------------------------------------
 
Starting ioBroker...
 
host.iobroker check instance "system.adapter.admin.0" for host "buildkitsandbox"
host.iobroker check instance "system.adapter.discovery.0" for host "buildkitsandbox"
host.iobroker check instance "system.adapter.backitup.0" for host "buildkitsandbox"

```

**Comment by hakarune** [comment] 2022-03-18 06:34
ip:8085 is "ERR_CONNECTION_REFUSED"

**Comment by buanet** [comment] 2022-03-18 07:27
```
    environment:
        - PUID=1000
        - PGID=100
        - TZ=America/Los_Angeles
        - UMASK_SET=002 #optional
        - CLEAN_TMP_DIR=1
        - VIRTUAL_HOST=iobroker.local
        - VIRTUAL_PORT=8085
```
Except `TZ` your ENVs are not valid. See https://docs.buanet.de/iobroker-docker-image/docs/#environment-variables-env
Even if your ENV PGID should be a SETGID, is 100 correct?

According to the log you get an permission error while correcting the hostname in iobroker config:
```
Hostname in ioBroker does not match the hostname of this container.
Updating hostname to  iobroker...
/opt/scripts/iobroker_startup.sh: line 205: /usr/bin/iobroker: Permission denied
iobroker host <hostname> 
```
Try setting ENVs `SETGID` and `SETUID` so it matches with the UID and GID of your mounted ioboker folder (/sharedfolders/Alt_External/docker_configs/iobroker). Hopefully this will fix the permission issue. 

I will also try reproducing your issue to make sure there is no bug with the hostname change. Log output looks a little strange in your case...  

Regards,
André

**Comment by buanet** [comment] 2022-03-18 17:10
I did some tests. Can not reproduce your issue. Your stack comes up without any problems. I only changed the folder for the mount. Please check the suggested things regarding your folder mount. 

Regards,
André

**Comment by hakarune** [comment] 2022-03-18 20:55
> I did some tests. Can not reproduce your issue. Your stack comes up without any problems. I only changed the folder for the mount. Please check the suggested things regarding your folder mount.
> 
> Regards, André

my enviromental variables are standard across docker. linuxserver.io even had a post here on how to set ID and GID (https://docs.linuxserver.io/general/understanding-puid-and-pgid). As for the timezone, that is a 100% valid unix recognized TZ, it's for the west coast of America for PST (-8:00). These variables are used with pretty much every docker I run and they work 100%. 

I have set the variables as you have suggested "SETID" and "SETGID", removed everything except TZ. Verified the ID and GID have access and full control of everything in the folders. I also changed hostname to same as the server. Network mode is still bridge like almost all of my dockers.

still no dice:
```

-----                                                                      -----
-----                             Docker-Image                             -----
-----                    image:               v6.1.0                       -----
-----                    build:               2022-03-14T07:29:48+00:00    -----
-----                                                                      -----
-----                               Versions                               -----
-----                    node:                v14.19.0                     -----
-----                    npm:                 6.14.16                      -----
-----                                                                      -----
-----                                 ENV                                  -----
-----                    SETGID:              100                          -----
-----                    SETUID:              1000                         -----
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                  Step 1 of 5: Preparing container                   -----
--------------------------------------------------------------------------------
 
Updating Linux packages on first run...
dpkg-preconfigure: unable to re-open stdin: 
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 32069 files and directories currently installed.)
Preparing to unpack .../libssl1.1_1.1.1k-1+deb11u2_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1k-1+deb11u2) over (1.1.1k-1+deb11u1) ...
Setting up libssl1.1:amd64 (1.1.1k-1+deb11u2) ...
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 32069 files and directories currently installed.)
Preparing to unpack .../nodejs_14.19.1-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (14.19.1-deb-1nodesource1) over (14.19.0-deb-1nodesource1) ...
Preparing to unpack .../openssl_1.1.1k-1+deb11u2_amd64.deb ...
Unpacking openssl (1.1.1k-1+deb11u2) over (1.1.1k-1+deb11u1) ...
Setting up nodejs (14.19.1-deb-1nodesource1) ...
Setting up openssl (1.1.1k-1+deb11u2) ...
Processing triggers for libc-bin (2.31-13+deb11u2) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Done.
 
Registering maintenance script as command...
Done.
 
Different UID and/ or GID is set by ENV.
Changing UID to 1000 and GID to 100...
usermod: no changes
groupmod: GID '100' already exists
Done.
 
--------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker installation             -----
--------------------------------------------------------------------------------
 
Existing installation of ioBroker detected in /opt/iobroker.
 
--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
(Re)Setting folder permissions (This might take a while! Please be patient!)...
Done.
 
Fixing "sudo-bug" by replacing sudo in iobroker with gosu...
Done.
 
Hostname in ioBroker does not match the hostname of this container.
Updating hostname to  omvnas...
/opt/scripts/iobroker_startup.sh: line 205: /usr/bin/iobroker: Permission denied
iobroker host <hostname>

Set host to given hostname


:
  iobroker host this               Initialize current host
  iobroker host set <hostname>     Set host with specified hostname
  iobroker host remove <hostname>  Remove host with specified hostname

Options:
  --help  Show help  [boolean]

Not enough non-option arguments: got 0, need at least 1
Done.
 
--------------------------------------------------------------------------------
-----                Step 4 of 5: Applying special settings                -----
--------------------------------------------------------------------------------
 
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).
 
--------------------------------------------------------------------------------
-----                    Step 5 of 5: ioBroker startup                     -----
--------------------------------------------------------------------------------
 
Starting ioBroker...
 
host.omvnas check instance "system.adapter.admin.0" for host "buildkitsandbox"
host.omvnas check instance "system.adapter.discovery.0" for host "buildkitsandbox"
host.omvnas check instance "system.adapter.backitup.0" for host "buildkitsandbox"

```

hostname of the server:
```
root@omvnas:/# hostname
omvnas
```

from iobrocker docker:
```
root@omvnas:/opt/iobroker# hostname
omvnas
```


Tried again setting the entire folder to 777 and setting network mode to host instead of bridge.
it sat at "Starting iobroker" for over 10 min.

 ```

--------------------------------------------------------------------------------
-------------------------     2022-03-18 13:48:46      -------------------------
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                 Welcome to your ioBroker-container!                  -----
-----                    Startupscript is now running.                     -----
-----                          Please be patient!                          -----
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                        Debugging information                         -----
-----                                                                      -----
-----                                System                                -----
-----                    arch:                x86_64                       -----
-----                    hostname:            omvnas                       -----
-----                                                                      -----
-----                             Docker-Image                             -----
-----                    image:               v6.1.0                       -----
-----                    build:               2022-03-14T07:29:48+00:00    -----
-----                                                                      -----
-----                               Versions                               -----
-----                    node:                v14.19.0                     -----
-----                    npm:                 6.14.16                      -----
-----                                                                      -----
-----                                 ENV                                  -----
-----                    SETGID:              100                          -----
-----                    SETUID:              1000                         -----
--------------------------------------------------------------------------------
 
--------------------------------------------------------------------------------
-----                  Step 1 of 5: Preparing container                   -----
--------------------------------------------------------------------------------
 
Updating Linux packages on first run...
dpkg-preconfigure: unable to re-open stdin: 
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 32069 files and directories currently installed.)
Preparing to unpack .../libssl1.1_1.1.1k-1+deb11u2_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1k-1+deb11u2) over (1.1.1k-1+deb11u1) ...
Setting up libssl1.1:amd64 (1.1.1k-1+deb11u2) ...
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 32069 files and directories currently installed.)
Preparing to unpack .../nodejs_14.19.1-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (14.19.1-deb-1nodesource1) over (14.19.0-deb-1nodesource1) ...
Preparing to unpack .../openssl_1.1.1k-1+deb11u2_amd64.deb ...
Unpacking openssl (1.1.1k-1+deb11u2) over (1.1.1k-1+deb11u1) ...
Setting up nodejs (14.19.1-deb-1nodesource1) ...
Setting up openssl (1.1.1k-1+deb11u2) ...
Processing triggers for libc-bin (2.31-13+deb11u2) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Done.
 
Registering maintenance script as command...
Done.
 
Different UID and/ or GID is set by ENV.
Changing UID to 1000 and GID to 100...
usermod: no changes
groupmod: GID '100' already exists
Done.
 
--------------------------------------------------------------------------------
-----             Step 2 of 5: Detecting ioBroker installation             -----
--------------------------------------------------------------------------------
 
Existing installation of ioBroker detected in /opt/iobroker.
 
--------------------------------------------------------------------------------
-----             Step 3 of 5: Checking ioBroker installation              -----
--------------------------------------------------------------------------------
 
(Re)Setting folder permissions (This might take a while! Please be patient!)...
Done.
 
Fixing "sudo-bug" by replacing sudo in iobroker with gosu...
Done.
 
/opt/scripts/iobroker_startup.sh: line 201: [: !=: unary operator expected
--------------------------------------------------------------------------------
-----                Step 4 of 5: Applying special settings                -----
--------------------------------------------------------------------------------
 
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information see ioBroker Docker Image Docs (https://docs.buanet.de/iobroker-docker-image/docs/).
 
--------------------------------------------------------------------------------
-----                    Step 5 of 5: ioBroker startup                     -----
--------------------------------------------------------------------------------
 
Starting ioBroker...
 
```

**Comment by buanet** [comment] 2022-03-18 23:45
> my enviromental variables are standard across docker. linuxserver.io even had a post here on how to set ID and GID (https://docs.linuxserver.io/general/understanding-puid-and-pgid). 

I'm sorry, but this is not correct. As you can read in the link you posted, PGID and PUID are just a standard for the linuxserver.io images. ioBroker is no linuxserver.io image. 

> Using the PUID and PGID allows **our containers** to map the container's internal user to a user on the host machine. All of **our containers** use this method of user mapping and should be applied accordingly.

**Our ioBroker container** uses only the environment variables listed in the [docs](https://docs.buanet.de/iobroker-docker-image/docs/#environment-variables-env). All other ENV will be ignored!

> Tried again setting the entire folder to 777 and setting network mode to host instead of bridge.
> it sat at "Starting iobroker" for over 10 min.

As you can see in the logfile, after setting the folder to 777 the permission issue disappears. So if you want to hear it or not, you got a permission error. The change of your network to `host` is no need.

As your ioBroker is still not starting and giving a `/opt/scripts/iobroker_startup.sh: line 201: [: !=: unary operator expected` when trying to set the hostname of your ioBroker instance reminds me to another issue: https://github.com/buanet/ioBroker.docker/issues/71 (sorry, only in german)

The root cause of this was, that the partition on which the iobroker folder was stored on the host (in your case `/sharedfolders/Alt_External/docker_configs/iobroker`) was mounted with the `noexec` flag. In NAS systems this is often activated by default for partitions where you normally only store data (not executing it). Please [check](https://unix.stackexchange.com/questions/91068/how-to-check-if-a-partition-is-mounted-as-noexec) if this is the case for you too.

Regards,
André

**Comment by hakarune** [comment] 2022-03-21 17:40
Sorry for the delay, work and family. 

Those EV have worked previously in all the dockers I've used, even ones not from Linuxserver. I missed your specific ones in the Env table at the bottom when setting up from  dockerhub and I apologize for that. They are correct now. Thank you for your patience. 

Not sure how there is a permission error on the folders when my main user is uid/gid set and created the folders for the iobroker docker on a volumed section owned by the user and group as well. But I can see if there's a folder or something within the main folder that's wrong. 

The HDD holding it all isn't noexec. 
Fstab: `/srv/dev-disk-by-label-External/          /export/Alt_External    none    bind,nofail      0 0`

Okay, going to set it back to bridged or dedicated network then. I don't like having dockers running as host. 

Not sure what else could be the issue. I can try disabling Calibre from 8081 and try running this again. Is there anything missing from my yml file or something that would be better if changed?

**Comment by buanet** [comment] 2022-03-21 20:02
> Sorry for the delay, work and family.

No worries, I know what you mean. :)

To make sure it is not any kind of issue with the mounted directory you can try to startup your container without any volume/ mount.

I found an old issue with a similar problem (also on omv). It's in german but it turned out that omv mounts all volumes with noexec by default: https://github.com/buanet/ioBroker.docker/issues/185#issuecomment-943284789
I'm not a Linux filesystem pro, but I think the issue is because of your filesystem does not allow to execute iobroker. 

The port redirection should not be a problem. I tried your compose and it worked. 

Regards,
André

**Comment by buanet** [comment] 2022-04-18 19:48
No further response received. I'll close this issue.

Regards,
André

**Closed by buanet** 2022-04-18 19:48 UTC

**Comment by hakarune** [comment] 2022-04-28 02:47
Sorry, have not had a chance to test anything since last comment. Had server issues and haven't had a chance to repair and try the fix. I'm hoping this weekend I'll be able to get everything back up and running 100% to try the fix.

**Comment by hakarune** [comment] 2022-05-10 20:33
> No further response received. I'll close this issue.
> 
> Regards,
> André 

I created a new install of debian and docker and tested and it wouldn't work on any mounted except the OS drive. I have gotten it to install now on the OS drive and using a docker volume instead of mounted bind. I can make it work this way instead. Thank you.
