### ISSUE TITLE
[v6.1] bash: /usr/bin/node: Operation not permitted

### ISSUE THREAD

**Issue by viceice** [buanet/ioBroker.docker#250] opened 2022-03-03 10:23 UTC
After upgrading jscontroller  from v3.3.x to v4.0.15, i get `EPERM` on logs for starting instances.

When trying manually starting node from root bash in container i get `bash: /usr/bin/node: Operation not permitted`

**Comment by viceice** [comment] 2022-03-03 10:24
I', using `ghcr.io/buanet/iobroker:v6.1.0@sha256:d8c2abe61385cd0a1462f3a8d9a001de33d58df43cc724e59283545a8cb080b6`

**Comment by viceice** [comment] 2022-03-03 10:53
OK, deleting and recreating container (with existing mounts/config) seems to fix the issue 😕

**Comment by DizzelPopitzel** [comment] 2022-03-14 12:37
I have a similar issue which is reproducable. When I'm starting a v5.2.0 image in my microk8s environment with an empty volume, everthing works as expected. I can install adapters and communicate with devices.

Now I do the same with a v6.1.0 - the one you've pushed 4 hours ago - as well with an empty volume. In this case I can run the welcome/setup wizzard and finish it, but the expected device discovery dialog does not appear. Instead I get this in the logs:

`Cannot get NPM version: Error: Command failed: npm -v
/usr/bin/env: ‘node’: Operation not permitted`

Restarting the host with the GUI does not bring back the web server. After deleting the pod k8s brings up a new container based on the previously created volume. Now I can install adapters and communicate with devices.

So just the first start is a problem.

**Comment by Apollon77** [comment] 2022-03-17 17:32
which js-controller ist used?

**Comment by jarvisquis** [comment] 2022-03-17 18:36
js-controller 4.0.21 is used

**Comment by Apollon77** [comment] 2022-03-17 20:49
the node capabilities need to be set anew ... so iob fix should be executed

**Comment by jarvisquis** [comment] 2022-03-18 15:25
ok I stopped admin adapter via WebUI and executed from within the container as root iob fix from /opt/iobroker. The output of the script looks fine for me:
```
root@iobroker-67cf4877f5-przqj:/opt/iobroker# iob fix
library: loaded
Library version=2022-02-10

==========================================================================

    Welcome to the ioBroker installation fixer!
    Script version: 2022-02-13

==========================================================================


==========================================================================
    Installing prerequisites (1/3)
==========================================================================

Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44,1 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39,4 kB]        
Get:4 https://deb.nodesource.com/node_14.x bullseye InRelease [4.586 B]        
Get:5 http://deb.debian.org/debian bullseye/main arm64 Packages [8.070 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [2.596 B]
Get:7 http://security.debian.org/debian-security bullseye-security/main arm64 Packages [121 kB]
Get:8 https://deb.nodesource.com/node_14.x bullseye/main arm64 Packages [773 B]
Fetched 8.398 kB in 4s (2.271 kB/s)
Reading package lists... Done
Installed gcc-c++
Installed python-dev

==========================================================================
    Checking ioBroker user and directory permissions (2/3)
==========================================================================

Created /etc/sudoers.d/iobroker
Fixing directory permissions...
This system does not support setting default permissions.
Do not use npm to manually install adapters unless you know what you are doing!

==========================================================================
    Checking autostart (3/3)
==========================================================================

Unsupported init system, cannot enable autostart!

==========================================================================

    Your installation was fixed successfully
    Run iobroker start to start ioBroker again!

==========================================================================

```
Then i tried to execute iob commands. But again the following errors occured:
```
root@iobroker-67cf4877f5-przqj:/opt/iobroker# iob start
sudo: unable to execute /usr/bin/node: Operation not permitted
root@iobroker-67cf4877f5-przqj:/opt/iobroker# iob
sudo: unable to execute /usr/bin/node: Operation not permitted
```

**Comment by buanet** [comment] 2022-03-18 17:30
What is the result of ```getcap $(eval readlink -f `which node`)```??

@DizzelPopitzel Do you use a raspberry pi 4 with arm64v8 image too??

**Comment by DizzelPopitzel** [comment] 2022-03-18 19:49
Yes,  raspberry pi 4 with arm64v8 image

**Comment by jarvisquis** [comment] 2022-03-18 20:39
Output of getcap is:
```
/usr/bin/node cap_net_bind_service,cap_net_admin,cap_net_raw=eip
```

**Comment by buanet** [comment] 2022-03-18 23:12
Just for note, running the docker image in a kubernetes cluster is not supported so far, as I did not tested it.
So it might work, but you also can face issues like this one :)

BUT

After some testing, I think I figured out the root cause. As @Apollon77 said your capabilities are not set correctly.
As long as `cap_net_admin` is set on node, but not set for the container you will get the "Permission denied" issue.
So there are two ways to hopefully get your setup working:
1. Set `cap_net_admin` to your container ([docker docs link](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities))
2. Correct the capabilities (removing `cap_net_admin`)  inside your container with
```
sudo setcap 'cap_net_bind_service,cap_net_raw=eip' `which node`
```
Can you try if this workaround works? 

@Apollon77 @AlCalzone I think we have to talk about our capabilities check in js-controller to detect kubernetes as we detect docker. As far as I could determine [this](https://github.com/ioBroker/ioBroker.js-controller/blob/1e7b7b9eeaf58a3d327637e8bb924f9611c1b269/packages/common/src/lib/common/tools.ts#L374) works for docker but not for kubernetes. 

Regards,
André

**Comment by DizzelPopitzel** [comment] 2022-03-19 09:49
Great! Adding `cap_net_admin` makes it run as expected. Thanks for your support.

**Comment by jarvisquis** [comment] 2022-03-20 19:46
@buanet Yes I know that this is not officially supported and I appreciate the support here ;)

Both proposed workarounds fix the issue. Thank You

**Comment by buanet** [comment] 2022-12-07 10:04
We did some tweaks to the Docker detection of ioBroker. Hopefully this prevents us from wrong capabilities settings as docker is detected more reliable.
However, I'll close this at this point. 
Thank you.

Regards,
André

**Closed by buanet** 2022-12-07 10:04 UTC
