### ISSUE TITLE
[Problem]: cannot pull most of the tags for ghcr.io/buanet/iobroker

### ISSUE THREAD

**Issue by EugenMayer** [buanet/ioBroker.docker#416] opened 2024-01-04 18:05 UTC
### Description / Beschreibung

Seems like most of the manifests on `ghcr.io/buanet/iobroker` are not pullable

### Image version

9.0.1

### Docker logs / Docker Protokoll

```shell
docker pull ghcr.io/buanet/iobroker:v9.0.1
v9.0.0: Pulling from buanet/iobroker
manifest unknown

docker pull ghcr.io/buanet/iobroker:v8.0.1
v8.0.1: Pulling from buanet/iobroker
manifest unknown

docker pull ghcr.io/buanet/iobroker:v8.0.0
v8.0.0: Pulling from buanet/iobroker
manifest unknown

docker pull ghcr.io/buanet/iobroker:v7.2.0
v7.2.0: Pulling from buanet/iobroker
manifest unknown

docker pull ghcr.io/buanet/iobroker:v7.1.2
-> pulls
```

am i missing something?

**Comment by buanet** [comment] 2024-01-04 18:39
> am i missing something?

Sure. Duplicate of #330

**Closed by buanet** 2024-01-04 18:39 UTC
